app:
  image: vfarcic/books-ms
  ports:
    - 8080
  links:
    - db:db
  environment:
    - SERVICE_NAME=books-ms
  log_driver: syslog
  log_opt:
    tag: books-ms

db:
  image: mongo:3-stretch
  log_driver: syslog
  log_opt:
    tag: books-ms
