app:
  image: 10.100.198.200:5000/books-ms
  ports:
    - 8080
  log_driver: syslog
  log_opt:
    syslog-address: tcp://10.100.192.200:25826
    syslog-tag: books-ms
  environment:
    - SERVICE_NAME=books-ms
    - DB_HOST=books-ms-db

app-blue:
  environment:
    - SERVICE_NAME=books-ms-blue
  extends:
    service: app

app-green:
  environment:
    - SERVICE_NAME=books-ms-green
  extends:
    service: app

db:
  container_name: books-ms-db
  image: mongo:3-stretch
  log_driver: syslog
  log_opt:
    syslog-address: tcp://10.100.192.200:25826
    syslog-tag: books-db
  environment:
    - SERVICE_NAME=books-db
